<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Work>
 */
class WorkFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $position = fake()->randomElement([
            "Software Developer",
            "Project Manager",
            "Marketing Specialist",
            "Customer Service Representative",
            "Financial Analyst",
            "Administrative Assistant",
            "Teacher",
            "Data Analyst",
            "Human Resources Manager",
            "Graphic Designer",
            "Sales Representative",
            "Nurse",
            "IT Support Specialist",
            "Logistics Coordinator",
            "Legal Assistant",
            "Web Developer",
            "Content Writer",
            "Event Planner",
            "Quality Assurance Engineer",
            "Product Manager",
            "Business Analyst",
            "Operations Manager",
            "Digital Marketing Manager",
            "Accountant",
            "Executive Assistant",
            "Mechanical Engineer",
            "Electrical Engineer",
            "Civil Engineer",
            "Architect",
            "Pharmacist",
            "Lab Technician",
            "Social Media Manager",
            "UX/UI Designer",
            "Technical Writer",
            "Recruiter",
            "Network Administrator",
            "Database Administrator",
            "Sales Manager",
            "Copywriter",
            "PR Specialist",
            "Supply Chain Manager",
            "HR Specialist",
            "Customer Success Manager",
            "Software Tester",
            "Mobile Developer",
            "SEO Specialist",
            "Biomedical Engineer",
            "Graphic Illustrator",
            "Industrial Designer",
            "Field Service Technician"
        ]);

        $level = fake()->randomElement([
            "Entry Level",
            "Associate",
            "Junior",
            "Mid-Level",
            "Senior",
            "Lead",
            "Manager",
            "Director",
            "Executive"
        ]);

        $industry = fake()->randomElement([
            "Information Technology",
            "Healthcare",
            "Finance",
            "Education",
            "Hospitality",
            "Manufacturing",
            "Retail",
            "Construction",
            "Automotive",
            "Telecommunications",
            "Marketing",
            "Media and Entertainment",
            "Agriculture",
            "Transportation",
            "Energy",
            "Real Estate",
            "Legal",
            "Consulting",
            "Non-Profit",
            "Government",
            "Insurance",
            "Engineering",
            "Food and Beverage",
            "Fashion",
            "Travel and Tourism",
            "Sports and Recreation",
            "Pharmaceutical",
            "Environmental",
            "Art and Design",
            "Human Resources",
            "Customer Service",
            "Sales",
            "Research and Development",
            "Science",
            "Writing and Editing",
            "Social Services",
            "Fitness and Wellness",
            "Security",
            "Event Planning",
            "Beauty and Cosmetics",
            "Telecommuting",
            "Freelance",
            "E-commerce",
            "Startups",
            "Music",
            "Aviation",
            "Maritime",
            "Architecture",
            "Biotechnology"
        ]);

        $specialization = fake()->randomElement([
            "Software Development",
            "Web Development",
            "Mobile App Development",
            "Database Administration",
            "Network Administration",
            "System Administration",
            "Cloud Computing",
            "Cybersecurity",
            "Data Science",
            "Machine Learning",
            "Artificial Intelligence",
            "Big Data Analytics",
            "DevOps",
            "Quality Assurance",
            "UI/UX Design",
            "Graphic Design",
            "Digital Marketing",
            "Content Writing",
            "Copywriting",
            "SEO/SEM",
            "Social Media Management",
            "Project Management",
            "Business Analysis",
            "Financial Analysis",
            "Human Resources Management",
            "Recruitment",
            "Training and Development",
            "Sales",
            "Customer Service",
            "Logistics and Supply Chain Management",
            "Operations Management",
            "Event Planning",
            "Legal",
            "Healthcare Management",
            "Teaching and Education",
            "Research and Development",
            "Consulting",
            "Public Relations",
            "Product Management",
            "Real Estate",
            "Construction Management",
            "Environmental Management",
            "Hospitality Management",
            "Retail Management",
            "Travel and Tourism",
            "Journalism",
            "Photography"
        ]);

        return [
            "company_name" => fake()->company(),
            "company_website" => 'https://www.techinnovators.com',
            "position_title" => $position,
            "position_level" => $level,
            "industry" => $industry,
            "specialization" => $specialization,
            "description" => fake()->paragraph(),
            "current" => fake()->randomElement([true, false]),
            "from" => fake()->dateTimeBetween('-5 years'),
            "to" => now(),
        ];
    }
}
